# ===========================================
# Exemplo: Storage com NFS + Istio
# ===========================================
#
# StorageClasses disponíveis:
#   - nfs-dynamic: Provisionamento automático (PV criado automaticamente)
#   - nfs-static:  Provisionamento manual (requer PV pré-criado)
#
# NFS Server: 192.168.56.20 (storage)
# NFS Path: /exports/k8s-volumes
# Acesso: http://<INGRESS_IP>/
# ===========================================

# ===========================================
# EXEMPLO 1: Usando nfs-dynamic (automático)
# ===========================================
# Com nfs-dynamic, basta criar o PVC e o PV é criado automaticamente

---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamic-demo
  labels:
    istio-injection: enabled
---
# PVC com provisionamento dinâmico - PV será criado automaticamente
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-dynamic
  namespace: dynamic-demo
spec:
  storageClassName: nfs-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dynamic
  namespace: dynamic-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-dynamic
  template:
    metadata:
      labels:
        app: nginx-dynamic
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-data
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-content
        image: busybox
        command: ['sh', '-c', 'echo "<h1>NFS Dynamic Storage</h1><p>Hostname: $(hostname)</p><p>Data: $(date)</p><p>PV criado automaticamente!</p>" > /data/index.html']
        volumeMounts:
        - name: web-data
          mountPath: /data
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: app-data-dynamic

# ===========================================
# EXEMPLO 2: Usando nfs-static (manual)
# ===========================================
# Com nfs-static, você precisa criar o PV manualmente antes do PVC

---
apiVersion: v1
kind: Namespace
metadata:
  name: static-demo
  labels:
    istio-injection: enabled
---
# PV manual - criado antes do PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv01
  labels:
    storage: nfs
spec:
  storageClassName: nfs-static
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.20
    path: /exports/k8s-volumes/static-pv01
---
# PVC que usa o PV manual
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-static
  namespace: static-demo
spec:
  storageClassName: nfs-static
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  namespace: static-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-data
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-content
        image: busybox
        command: ['sh', '-c', 'echo "<h1>NFS Static Storage</h1><p>Hostname: $(hostname)</p><p>Data: $(date)</p><p>PV criado manualmente!</p>" > /data/index.html']
        volumeMounts:
        - name: web-data
          mountPath: /data
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: app-data-static

# ===========================================
# EXEMPLO 3: PV com claimRef (binding direto)
# ===========================================
# Use claimRef quando precisar garantir que um PV específico
# seja vinculado a um PVC específico (como o Karpor usa)

---
apiVersion: v1
kind: Namespace
metadata:
  name: claimref-demo
---
# PV com claimRef - reservado para um PVC específico
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reserved-pv
spec:
  storageClassName: nfs-static
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: claimref-demo
    name: reserved-pvc
  nfs:
    server: 192.168.56.20
    path: /exports/k8s-volumes/reserved-data
---
# PVC que será automaticamente vinculado ao PV acima
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reserved-pvc
  namespace: claimref-demo
spec:
  storageClassName: nfs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# ===========================================
# Services e Istio (para os exemplos acima)
# ===========================================
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dynamic
  namespace: dynamic-demo
spec:
  selector:
    app: nginx-dynamic
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static
  namespace: static-demo
spec:
  selector:
    app: nginx-static
  ports:
  - port: 80
    targetPort: 80
---
# Istio Gateway para demo
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: nfs-demo-gateway
  namespace: dynamic-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "nfs-dynamic.local"
    - "nfs-static.local"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx-dynamic
  namespace: dynamic-demo
spec:
  hosts:
  - "nfs-dynamic.local"
  gateways:
  - nfs-demo-gateway
  http:
  - route:
    - destination:
        host: nginx-dynamic
        port:
          number: 80
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx-static
  namespace: static-demo
spec:
  hosts:
  - "nfs-static.local"
  gateways:
  - dynamic-demo/nfs-demo-gateway
  http:
  - route:
    - destination:
        host: nginx-static.static-demo.svc.cluster.local
        port:
          number: 80
